### ISSUE TITLE
Issues about the installation guide 

### ISSUE THREAD

**Issue by Mizumo-prjkt** [RandomCoderOrg/ubuntu-on-android#182]
The guide mentions start using 'udroid' in shell to start, it didn't start

![Screenshot_20220803-065851_Termux.jpg](https://user-images.githubusercontent.com/70519093/182487650-d11a2316-3a81-49c9-adca-aa9de23c3a8b.jpg)

![Screenshot_20220803-065855_Termux.jpg](https://user-images.githubusercontent.com/70519093/182487660-059021df-f8fc-409c-b0c3-5205c7e25846.jpg)

But if you try `proot-distro login udroid-impish-xfce4` it starts

![Screenshot_20220803-065911_Termux.jpg](https://user-images.githubusercontent.com/70519093/182487724-810f4028-ad67-44c6-96d9-b9cac9328964.jpg)

I think someone should modify the guide or just fix how the installer script or the udroid in the `$PREFIX/bin` works.

**Comment by AnninoDr4** [comment]
@SUFandom Thanks for reaching us!
this issue is patched at [`RandomCoderOrg/fs-manager-udroid/36f2a7e`](https://github.com/RandomCoderOrg/fs-manager-udroid/commit/36f2a7e375cae2738bde2960f727bb965d856d66)

### cause of issue
standard redirection `>` failed to create new file which caused the script to fail

<hr>

#### correct login method
actual way to login is
```bash
udroid -l <varient_name>
```
> replace <variant_name> with xfce4 or raw
> checkout https://udroid-rc.gitbook.io/udroid-wiki/suites/ubuntu-21.10#installation for available variants  
> well do upgrade in docs to remove confusion

#### `dbus`
dbus & `shared-tmp` fix is enabled by default with udroid script

and the option `--enables-dbus-vnc` is no longer available
