### ISSUE TITLE
How to install Postgresql in proot-distro?

### ISSUE THREAD

**Issue by ask9027** [RandomCoderOrg/ubuntu-on-android#200]
Recently i installed Postgresql in ubuntu(Termux) but fail to start server.
Please help me setup postgresql in ubuntu(Termux).
i know there is postgresql package in termux repo but it has limitations.

**Comment by ask9027** [comment]
??

**Comment by SaicharanKandukuri** [comment]
Looks like postgresql have some issues with `proot` ( it won't work properly in root cause of I'd 0 hack in proot )

But it's just with the `root` user having a lot of trouble.

After some workarounds I managed to start and login posgres cluster SQL

Here is what you can do

Login to a non-root user ( ex: `udroid` its udroid de build )

> read this for creating your own non-root users in proot environments: [udroid_wiki/non-root-users](https://udroid-rc.gitbook.io/udroid-wiki/using-udroid/non-root-users)


Then chown the ssh key for current user
```bash
chown $USER:$USER "/etc/ssl/private/ssl-cert-snakeoil.key"
```

Create a cluster
```bash
pg_createcluster 14 main --start
```

Connect to cluster with default db **postgres**

```bash
psql -d postgres
```

> That should work

![Screenshot_20221024-214607_Termux.jpg](https://user-images.githubusercontent.com/68287637/197584381-a366040d-51ef-4edb-961c-78cc51a20d1e.jpg)
![Screenshot_20221024-222814_Termux.jpg](https://user-images.githubusercontent.com/68287637/197584410-5e596fb2-4dd6-4acb-aa3c-569165600f6a.jpg)


> And sorry for the late response I was on a vacation ✌️

**Comment by ask9027** [comment]
> Looks like postgresql have some issues with `proot` ( it won't work properly in root cause of I'd 0 hack in proot )
> 
> But it's just with the `root` user having a lot of trouble.
> 
> After some workarounds I managed to start and login posgres cluster SQL
> 
> Here is what you can do
> 
> Login to a non-root user ( ex: `udroid` its udroid de build )
> 
> > read this for creating your own non-root users in proot environments: [udroid_wiki/non-root-users](https://udroid-rc.gitbook.io/udroid-wiki/using-udroid/non-root-users)
> 
> Then chown the ssh key for current user
> 
> ```shell
> chown $USER:$USER "/etc/ssl/private/ssl-cert-snakeoil.key"
> ```
> 
> Create a cluster
> 
> ```shell
> pg_createcluster 14 main --start
> ```
> 
> Connect to cluster with default db **postgres**
> 
> ```shell
> psql -d postgres
> ```
> 
> > That should work
> 
> ![Screenshot_20221024-214607_Termux.jpg](https://user-images.githubusercontent.com/68287637/197584381-a366040d-51ef-4edb-961c-78cc51a20d1e.jpg) ![Screenshot_20221024-222814_Termux.jpg](https://user-images.githubusercontent.com/68287637/197584410-5e596fb2-4dd6-4acb-aa3c-569165600f6a.jpg)
> 
> > And sorry for the late response I was on a vacation ✌️

Your Late response is very helpfull and usefull 👌
