### ISSUE TITLE
"Scale" does not seem to work

### ISSUE THREAD

**Issue by mizzunet** [RandomCoderOrg/ubuntu-on-android#21]
![Screenshot_20210622-025717](https://user-images.githubusercontent.com/10193999/122830482-03167500-d306-11eb-9cfb-8942a3e47314.png)

This scale setting doesn't seem to work,
This is what happens when zooming out if changed 

![Screenshot_20210622-025740](https://user-images.githubusercontent.com/10193999/122830541-1b868f80-d306-11eb-9d47-6684d970e291.png)

It did work fine Ubuntu xfce on AndroNix's, https://andronix.app/

It is handy that I wouldn't need to zoom if the scale is 2x as everything can be read.

**Comment by SaicharanKandukuri** [comment]
I didn't came to this part yet
So open for suggestions

**Comment by ghost** [comment]
keep in mind that you're using the latest version of ubuntu under proot. it's been buggy and you're on newer version of tigervncserver too as compared to andronix. it uses 18.04 or 20.04 which were much stable for proot.

this may cause because of that. my device's native resolution 2264x1080, and I use 1508x720 which makes the text more visible. just use -geometry with that in starting and it will appear like this:-
![IMG-20210620-WA0003](https://user-images.githubusercontent.com/65938569/122864209-d54f2180-d341-11eb-98f0-f1a8e199da3b.jpg)
![5](https://user-images.githubusercontent.com/65938569/122864236-df712000-d341-11eb-8629-04fbbd0f400a.jpg)
and it works same for this too. also not recommended to change resolution from display directly to avoid further problems...

**Comment by SaicharanKandukuri** [comment]
@mizzunet this feature seems to be important! until I implement this in the next fs release file here is a hack to make it happen like this 
![Screenshot_20210622-112351_NetHunter KeX](https://user-images.githubusercontent.com/68287637/122871488-b99d4880-d34c-11eb-86c9-aa62d849d83b.jpg)

<hr>

we need export env variables ( `GDK_SCALE`, `QT_SCALE_FACTOR`, `XCURSOR_SIZE=48` ) before vncserver executes `startxfce4`
so change your `~/.vnc/xstartup` with cmd `nano ~/.vnc/xstartup` and change it to like this

```bash
#!/bin/bash
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADRESS
export PULSE_SERVER=127.0.0.1
export GDK_SCALE=2
export XCURSOR_SIZE=48
export QT_SCALE_FACTOR=2
exec startxfce4
```

after starting the server with `vncserver` and goto **Applications>Settings>Appearence** and in the window goto *settings*
and change window scaling to 2x

and as @GxmerSam said don't try to change resolution from vnc it makes things look bad
to make resolution match your device automatically check this issue #22 

You can play with that values to make them suitable for you
Hope this helps you out

**Comment by mizzunet** [comment]
@saicharankandakuri thank you, that did the job
