### ISSUE TITLE
Some questions with graphics acceleration

### ISSUE THREAD

**Issue by supechicken** [RandomCoderOrg/ubuntu-on-android#53]
Hello, I have some question about graphics
 acceleration with this project:

-  Do the Termux:Wayland app necessery for acceleration? (The repo to that app is down)
- How can it acheive without getting access to drm gpu device (`/dev/dri/card*`)

Thanks for any answer :)

**Comment by SaicharanKandukuri** [comment]
> Do the Termux:Wayland app necessery for acceleration? 

Yes but repo is back under active maintenance but the key devoloper giving up on it so it may take some time to make comfy for best case usage 
Goto: https://github.com/termux/termux-x11

> How can it acheive without getting access to drm gpu device (/dev/dri/card*)

For now most device vendors use Hardware Abstraction layers so that no software in userspace could read write or not even see it directly. It get tricky more with device specific methods for accessing that part. But for OnePlus  6 devices I heard about a way of making it possible cause of mainline Linux kernal support (may be)which lead to direct , in other devices accessing with root and recomping libGL.so (which is so experimental) is only known way to access it

> Thanks for any answer :)

 You're very welcome 👍

**Comment by supechicken** [comment]
Got it, the gl convert is done by `gl4es` and the rendering (and acceleration) part is done by the wayland plugin using some android api (correct me if I wrong)

Thanks again😀

**Comment by SaicharanKandukuri** [comment]
it works like this 
Wayland plugin + liblorie (Library that allows moving rendering to different processes with events support)
I think there is no `gles` 
https://github.com/twaik/liblorie
